### ISSUE TITLE
No ability to use different X-buttons for scroll and middle button

### ISSUE THREAD

**Issue by ArmanHayots** [Seelge/TrackballScroll#12]
So trackball becomes useless in apps like autodesk 3dsmax, where scroll used for zooming and middle button press for panning.

**Comment by Seelge** [comment]
Thank you for your feedback. Currently both X-buttons are mapped to the same behavior. What functionality would be optimal to you? Would being able to enable/disable the hook per X-button be sufficient?

**Comment by ArmanHayots** [comment]
Thank thee too for a best solution for problems caused by logitech stupidity.
 I think it can be done with 2 switches — «use different buttons for scroll and middle» and «swap scroll and middle buttons». This also can be done via one 3-state switch — «default behavior/X1 scroll, X2 middle / X1 middle, X2 scroll».

**Comment by Seelge** [comment]
@ArmanHayots 
v3 should satisfy your requirements. X1/2 buttons can be enabled/disabled in the tray menu. Disabled buttons are ignored by the TrackballScroll (i.e the default driver settings apply).

**Comment by ArmanHayots** [comment]
A little misunderstanding here. I'd talked about using different buttons for different actions, e.g. X1 for middle click and X2 for scroll and vice-versa. Otherwise usage of things like 3DSMax or Blender turns into hell.

**Comment by Seelge** [comment]
The configuration is not intuitive since it requires both TrackballScroll and Logitech SetPoint but it works using the following settings.

X1 button for middle click only:
- Logitech SetPoint: set button 3 to `other` + `middle mouse button` (seems to be only available for button 3 but not 4)
- TrackballScroll: ~~deactivate `use button X1`~~ does not matter since TrackballScroll will ignore middle button clicks

X2 button for scrolling only:
- Logitech SetPoint: set button 4 to `default` (=X2)
- TrackballScroll: optionally deactivate `emulate middle button when not scrolling` (requires v4).

Notes:
- Listed SetPoint settings are translations to english and may be called slightly different.
- Tested with blender.
